config/routes.rb
Rails.application.routes.draw do
  resources :hangouts
  resources :friendships
  devise_for :users
  resources :users, only: [:show]
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/hangout.rb
class Hangout < ApplicationRecord
    belongs_to :creator, class_name => "User"
    has_many :attendees, through: :hangout_booking, source: :hangout
end

app/models/hangout_booking.rb
class HangoutBooking < ApplicationRecord
  belongs_to :hangout
  has_many :attendees, class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true

  has_many :hangouts

  has_many :friendships
  has_many :friends, :through => :friendships
  #https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address
  #for troubleshooting username info
  # has_many friends,
  # friends belong to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[ show edit update destroy ]

  # GET /friendships or /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1 or /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships or /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to friendship_url(@friendship), notice: "Friendship was successfully created." }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1 or /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to friendship_url(@friendship), notice: "Friendship was successfully updated." }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friendships_url, notice: "Friendship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy)
    end
end

app/controllers/hangouts_controller.rb
class HangoutsController < ApplicationController
  before_action :set_hangout, only: %i[ show edit update destroy ]

  # GET /hangouts or /hangouts.json
  def index
    @hangouts = Hangout.all
  end

  # GET /hangouts/1 or /hangouts/1.json
  def show
  end

  # GET /hangouts/new
  def new
    @hangout = Hangout.new
  end

  # GET /hangouts/1/edit
  def edit
  end

  # POST /hangouts or /hangouts.json
  def create
    @hangout = Hangout.new(hangout_params)

    respond_to do |format|
      if @hangout.save
        format.html { redirect_to hangout_url(@hangout), notice: "Hangout was successfully created." }
        format.json { render :show, status: :created, location: @hangout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hangout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hangouts/1 or /hangouts/1.json
  def update
    respond_to do |format|
      if @hangout.update(hangout_params)
        format.html { redirect_to hangout_url(@hangout), notice: "Hangout was successfully updated." }
        format.json { render :show, status: :ok, location: @hangout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hangout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hangouts/1 or /hangouts/1.json
  def destroy
    @hangout.destroy

    respond_to do |format|
      format.html { redirect_to hangouts_url, notice: "Hangout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hangout
      @hangout = Hangout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hangout_params
      params.require(:hangout).permit(:date, :time, :creator_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship) do |form| %>
  <% if friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :friend_id, style: "display: block" %>
    <%= form.number_field :friend_id %>
  </div>

  <div>
    <%= form.label :create, style: "display: block" %>
    <%= form.text_field :create %>
  </div>

  <div>
    <%= form.label :destroy, style: "display: block" %>
    <%= form.text_field :destroy %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
<div id="<%= dom_id friendship %>">
  <p>
    <strong>User:</strong>
    <%= friendship.user_id %>
  </p>

  <p>
    <strong>Friend:</strong>
    <%= friendship.friend_id %>
  </p>

  <p>
    <strong>Create:</strong>
    <%= friendship.create %>
  </p>

  <p>
    <strong>Destroy:</strong>
    <%= friendship.destroy %>
  </p>

</div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<div>
  <div id="users">
  <% for user in @users %>
    <div class="user">
      <p>
        <strong><%= user.username %></strong>
        <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
        <div class="clear"></div>
      </p>
    </div>
  <% end %>
</div>



<p style="color: green"><%= notice %></p>

<h1>Friendships</h1>

<div id="friendships">
  <% @friendships.each do |friendship| %>
    <%= render friendship %>
    <p>
      <%= link_to "Show this friendship", friendship %>
    </p>
  <% end %>
</div>

<%= link_to "New friendship", new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friendship %>

<div>
  <%= link_to "Edit this friendship", edit_friendship_path(@friendship) %> |
  <%= link_to "Back to friendships", friendships_path %>

  <%= button_to "Destroy this friendship", @friendship, method: :delete %>
</div>

app/views/hangouts/_form.html.erb
<%= form_with(model: hangout) do |form| %>
  <% if hangout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hangout.errors.count, "error") %> prohibited this hangout from being saved:</h2>

      <ul>
        <% hangout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.time_field :time %>
  </div>

  <div>
    <%= form.label :creator_id, style: "display: block" %>
    <%= form.number_field :creator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hangouts/_hangout.html.erb
<div id="<%= dom_id hangout %>">
  <p>
    <strong>Date:</strong>
    <%= hangout.date %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= hangout.time %>
  </p>

  <p>
    <strong>Creator:</strong>
    <%= hangout.creator_id %>
  </p>

</div>

app/views/hangouts/edit.html.erb
<h1>Editing hangout</h1>

<%= render "form", hangout: @hangout %>

<br>

<div>
  <%= link_to "Show this hangout", @hangout %> |
  <%= link_to "Back to hangouts", hangouts_path %>
</div>

app/views/hangouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hangouts</h1>

<div id="hangouts">
  <% @hangouts.each do |hangout| %>
    <%= render hangout %>
    <p>
      <%= link_to "Show this hangout", hangout %>
    </p>
  <% end %>
</div>

<%= link_to "New hangout", new_hangout_path %>

app/views/hangouts/new.html.erb
<h1>New hangout</h1>

<%= render "form", hangout: @hangout %>

<br>

<div>
  <%= link_to "Back to hangouts", hangouts_path %>
</div>

app/views/hangouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hangout %>

<div>
  <%= link_to "Edit this hangout", edit_hangout_path(@hangout) %> |
  <%= link_to "Back to hangouts", hangouts_path %>

  <%= button_to "Destroy this hangout", @hangout, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangoutly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>